#!/bin/bash
npm install nodemon -g
npm install body-parser -g
npm install express -g
npm install grunt -g
npm install grunt-bower-task -g
npm install grunt-contrib-concat -g
npm install grunt-contrib-copy -g
npm install grunt-contrib-jshint -g
npm install grunt-contrib-qunit -g
npm install grunt-contrib-uglify -g
npm install grunt-contrib-watch -g
npm install grunt-contrib-sass -g
npm install koa -g
npm install koa-router -g
npm install koa-static -g
npm install sass -g
npm install koa-static-server -g
npm install koa-send -g
npm install koa-sendfile -g
